_format_version: "2.1"
_transform: true
services:
- connect_timeout: 60000
  host: mysvc-endpoint.internal
  name: My-Awesome-SVC
  path: /
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - name: my-api
    paths:
    - /my/api
    path_handling: v0
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
  plugins:
  - name: acl
    config:
      allow:
      - mysvc-consumers
      deny: []
      hide_groups_header: false
    enabled: true
    protocols:
    - grpc
    - grpcs
    - http
    - https
consumers:
- username: myapp
  keyauth_credentials:
  - key: myapp_key
  acls:
  - group: mysvc-consumers
  - group: anothersvc-consumers
plugins:
- name: prometheus
  enabled: true
  protocols:
  - grpc
  - grpcs
  - http
  - https
